package Banque;


/**
* Banque/banqueServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* jeudi 24 septembre 2026 01 h 57 EAT
*/

public abstract class banqueServicePOA extends org.omg.PortableServer.Servant
 implements Banque.banqueServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("faireDepot", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Banque/banqueService/faireDepot
       {
         int id = in.read_long ();
         double montant = in.read_double ();
         Banque.Compte $result = null;
         $result = this.faireDepot (id, montant);
         out = $rh.createReply();
         Banque.CompteHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Banque/banqueService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public banqueService _this() 
  {
    return banqueServiceHelper.narrow(
    super._this_object());
  }

  public banqueService _this(org.omg.CORBA.ORB orb) 
  {
    return banqueServiceHelper.narrow(
    super._this_object(orb));
  }


} // class banqueServicePOA
