package Banque;


/**
* Banque/Compte.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* jeudi 24 septembre 2026 01 h 57 EAT
*/

public final class Compte implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String nom = null;
  public double solde = (double)0;

  public Compte ()
  {
  } // ctor

  public Compte (int _id, String _nom, double _solde)
  {
    id = _id;
    nom = _nom;
    solde = _solde;
  } // ctor

} // class Compte
