package BanqueModule;

/**
* BanqueModule/banqueServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* mercredi 23 septembre 2026 14 h 03 EAT
*/

public final class banqueServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public BanqueModule.banqueService value = null;

  public banqueServiceHolder ()
  {
  }

  public banqueServiceHolder (BanqueModule.banqueService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BanqueModule.banqueServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BanqueModule.banqueServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BanqueModule.banqueServiceHelper.type ();
  }

}
