package BanqueModule;


/**
* BanqueModule/banqueServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* mercredi 23 septembre 2026 14 h 03 EAT
*/

abstract public class banqueServiceHelper
{
  private static String  _id = "IDL:BanqueModule/banqueService:1.0";

  public static void insert (org.omg.CORBA.Any a, BanqueModule.banqueService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static BanqueModule.banqueService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (BanqueModule.banqueServiceHelper.id (), "banqueService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static BanqueModule.banqueService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_banqueServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, BanqueModule.banqueService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static BanqueModule.banqueService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BanqueModule.banqueService)
      return (BanqueModule.banqueService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BanqueModule._banqueServiceStub stub = new BanqueModule._banqueServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static BanqueModule.banqueService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof BanqueModule.banqueService)
      return (BanqueModule.banqueService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      BanqueModule._banqueServiceStub stub = new BanqueModule._banqueServiceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
