package BanqueModule;


/**
* BanqueModule/banqueService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* mercredi 23 septembre 2026 14 h 03 EAT
*/

public interface banqueService extends banqueServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface banqueService
