package BanqueModule;


/**
* BanqueModule/banqueServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* mercredi 23 septembre 2026 14 h 03 EAT
*/

public interface banqueServiceOperations 
{
  boolean faireDepot (int idCompte, double montant);
} // interface banqueServiceOperations
