package BanqueModule;

/**
* BanqueModule/CompteDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* mercredi 23 septembre 2026 14 h 03 EAT
*/

public final class CompteDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public BanqueModule.CompteDTO value = null;

  public CompteDTOHolder ()
  {
  }

  public CompteDTOHolder (BanqueModule.CompteDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = BanqueModule.CompteDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    BanqueModule.CompteDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return BanqueModule.CompteDTOHelper.type ();
  }

}
