package BanqueModule;


/**
* BanqueModule/CompteDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* mercredi 23 septembre 2026 14 h 03 EAT
*/

public final class CompteDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String nom = null;

  public CompteDTO ()
  {
  } // ctor

  public CompteDTO (int _id, String _nom)
  {
    id = _id;
    nom = _nom;
  } // ctor

} // class CompteDTO
