// This file is generated by omniidl (C++ backend) - omniORB_4_3. Do not edit.

#include "banque.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

OMNI_MAYBE_UNUSED static const char* _0RL_library_version = omniORB_4_3;



void
BanqueModule::CompteDTO::operator>>= (cdrStream &_n) const
{
  id >>= _n;
  _n.marshalString(nom,0);

}

void
BanqueModule::CompteDTO::operator<<= (cdrStream &_n)
{
  (::CORBA::Long&)id <<= _n;
  nom = _n.unmarshalString(0);

}

BanqueModule::banqueService_ptr BanqueModule::banqueService_Helper::_nil() {
  return ::BanqueModule::banqueService::_nil();
}

::CORBA::Boolean BanqueModule::banqueService_Helper::is_nil(::BanqueModule::banqueService_ptr p) {
  return ::CORBA::is_nil(p);

}

void BanqueModule::banqueService_Helper::release(::BanqueModule::banqueService_ptr p) {
  ::CORBA::release(p);
}

void BanqueModule::banqueService_Helper::marshalObjRef(::BanqueModule::banqueService_ptr obj, cdrStream& s) {
  ::BanqueModule::banqueService::_marshalObjRef(obj, s);
}

BanqueModule::banqueService_ptr BanqueModule::banqueService_Helper::unmarshalObjRef(cdrStream& s) {
  return ::BanqueModule::banqueService::_unmarshalObjRef(s);
}

void BanqueModule::banqueService_Helper::duplicate(::BanqueModule::banqueService_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

BanqueModule::banqueService_ptr
BanqueModule::banqueService::_duplicate(::BanqueModule::banqueService_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

BanqueModule::banqueService_ptr
BanqueModule::banqueService::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


BanqueModule::banqueService_ptr
BanqueModule::banqueService::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

BanqueModule::banqueService_ptr
BanqueModule::banqueService::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_banqueService _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_banqueService* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_banqueService;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* BanqueModule::banqueService::_PD_repoId = "IDL:BanqueModule/banqueService:1.0";


BanqueModule::_objref_banqueService::~_objref_banqueService() {
  
}


BanqueModule::_objref_banqueService::_objref_banqueService(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::BanqueModule::banqueService::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
BanqueModule::_objref_banqueService::_ptrToObjRef(const char* id)
{
  if (id == ::BanqueModule::banqueService::_PD_repoId)
    return (::BanqueModule::banqueService_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::BanqueModule::banqueService::_PD_repoId))
    return (::BanqueModule::banqueService_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for BanqueModule::banqueService::faireDepot

// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_clong_i_cdouble
class _0RL_cd_586baeac1f53af63_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_586baeac1f53af63_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_586baeac1f53af63_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_586baeac1f53af63_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;

}

void _0RL_cd_586baeac1f53af63_00000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_586baeac1f53af63_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_586baeac1f53af63_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_586baeac1f53af63_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_586baeac1f53af63_00000000* tcd = (_0RL_cd_586baeac1f53af63_00000000*)cd;
  BanqueModule::_impl_banqueService* impl = (BanqueModule::_impl_banqueService*) svnt->_ptrToInterface(BanqueModule::banqueService::_PD_repoId);
  tcd->result = impl->faireDepot(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean BanqueModule::_objref_banqueService::faireDepot(::CORBA::Long idCompte, ::CORBA::Double montant)
{
  _0RL_cd_586baeac1f53af63_00000000 _call_desc(_0RL_lcfn_586baeac1f53af63_10000000, "faireDepot", 11);
  _call_desc.arg_0 = idCompte;
  _call_desc.arg_1 = montant;

  _invoke(_call_desc);
  return _call_desc.result;


}

BanqueModule::_pof_banqueService::~_pof_banqueService() {}


omniObjRef*
BanqueModule::_pof_banqueService::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::BanqueModule::_objref_banqueService(ior, id);
}


::CORBA::Boolean
BanqueModule::_pof_banqueService::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::BanqueModule::banqueService::_PD_repoId))
    return 1;
  
  return 0;
}

const BanqueModule::_pof_banqueService _the_pof_BanqueModule_mbanqueService;

BanqueModule::_impl_banqueService::~_impl_banqueService() {}


::CORBA::Boolean
BanqueModule::_impl_banqueService::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "faireDepot")) {

    _0RL_cd_586baeac1f53af63_00000000 _call_desc(_0RL_lcfn_586baeac1f53af63_10000000, "faireDepot", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
BanqueModule::_impl_banqueService::_ptrToInterface(const char* id)
{
  if (id == ::BanqueModule::banqueService::_PD_repoId)
    return (::BanqueModule::_impl_banqueService*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::BanqueModule::banqueService::_PD_repoId))
    return (::BanqueModule::_impl_banqueService*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
BanqueModule::_impl_banqueService::_mostDerivedRepoId()
{
  return ::BanqueModule::banqueService::_PD_repoId;
}

POA_BanqueModule::banqueService::~banqueService() {}

