module Banque {

    struct Compte {
        long id;
        string nom;
        double solde;
    };

    interface banqueService {
        Compte faireDepot(in long id , in double montant);
    };

};