package Banque;


/**
* Banque/banqueServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* jeudi 24 septembre 2026 01 h 57 EAT
*/

public interface banqueServiceOperations 
{
  Banque.Compte faireDepot (int id, double montant);
} // interface banqueServiceOperations
