package Banque;

/**
* Banque/banqueServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ../C++/banque.idl
* jeudi 24 septembre 2026 01 h 57 EAT
*/

public final class banqueServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public Banque.banqueService value = null;

  public banqueServiceHolder ()
  {
  }

  public banqueServiceHolder (Banque.banqueService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Banque.banqueServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Banque.banqueServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Banque.banqueServiceHelper.type ();
  }

}
